### PR TITLE
Remove hardcoded debug build type

### PR DESCRIPTION
**Pull request by Schwo0ps**

### CODE REVIEW

**Review by rsinnet — COMMENTED** [review]
Needs to be tested.

**Comment by Schwo0ps** [comment]
@zzv2 @rsinnet What do we want to do about this?

**Comment by rsinnet** [comment]
We need to test before we make this change.

**Comment by Schwo0ps** [comment]
@zzv2 @rsinnet Do we even use this repo? If not, I'm closing.

**Comment by rsinnet** [comment]
This is only for Flippy v1 :nail_care: :coffin:

**Pull request closed without merging**
